import os

from dotenv import load_dotenv
from google import genai


# =========================================================
# LOAD ENVIRONMENT VARIABLES
# =========================================================

load_dotenv()


# =========================================================
# GET GEMINI API KEY
# =========================================================

api_key = os.getenv(
    "GEMINI_API_KEY"
)


if not api_key:

    raise ValueError(
        "GEMINI_API_KEY was not found."
    )


# =========================================================
# CREATE GEMINI CLIENT
# =========================================================

client = genai.Client(
    api_key=api_key
)


# =========================================================
# CLEAN SQL
# =========================================================

def clean_sql(
    sql_query: str
) -> str:
    """
    Clean SQL generated by Gemini.
    """

    sql_query = sql_query.strip()


    # -----------------------------------------------------
    # REMOVE MARKDOWN SQL CODE FENCE
    # -----------------------------------------------------

    if sql_query.startswith(
        "```sql"
    ):

        sql_query = sql_query[
            len("```sql"):
        ]


    elif sql_query.startswith(
        "```"
    ):

        sql_query = sql_query[
            len("```"):
        ]


    if sql_query.endswith(
        "```"
    ):

        sql_query = sql_query[
            :-3
        ]


    sql_query = sql_query.strip()


    if not sql_query:

        raise ValueError(
            "Gemini returned an empty SQL query."
        )


    return sql_query


# =========================================================
# GENERATE SQL
# =========================================================

def generate_sql(
    user_question: str,
    schema_context: str
) -> str:
    """
    Generate a SQLite SELECT query from
    a natural-language question.
    """

    if not user_question:

        raise ValueError(
            "User question cannot be empty."
        )


    if not schema_context:

        raise ValueError(
            "Schema context cannot be empty."
        )


    # =====================================================
    # TEXT-TO-SQL PROMPT
    # =====================================================

    prompt = f"""
You are a professional Business Intelligence
Text-to-SQL assistant.

Your task is to convert the user's natural-language
question into a valid SQLite SQL query.

DATABASE TABLE:
dataset

RELEVANT DATABASE SCHEMA:
{schema_context}

USER QUESTION:
{user_question}


=========================================================
SQL GENERATION RULES
=========================================================

1. Return ONLY SQL.

2. The SQL must be a SELECT query.

3. Use only the table named dataset.

4. Use only columns that exist in the provided schema.

5. Never invent column names.

6. Do not use INSERT.

7. Do not use UPDATE.

8. Do not use DELETE.

9. Do not use DROP.

10. Do not use ALTER.

11. Do not use CREATE.

12. Do not use PRAGMA.

13. Do not use ATTACH.

14. Do not return Markdown.

15. Do not return ```sql.

16. The SQL must be compatible with SQLite.

17. Use appropriate aggregation functions such as:
    SUM
    AVG
    COUNT
    MIN
    MAX

18. When the question asks for a total, use SUM.

19. When the question asks for an average, use AVG.

20. When the question asks how many records/items exist,
    use COUNT.

21. When the question asks for a ranking such as:
    highest
    lowest
    most
    least
    top
    bottom

    use ORDER BY and LIMIT when appropriate.

22. When a ranking question asks which category,
    city, product, customer, or other dimension
    has the highest/lowest value, return BOTH:

    a. The dimension column.
    b. The calculated metric.

23. Give the calculated metric a clear alias.

24. Example:

    User question:
    Which city generated the highest revenue?

    Correct SQL:

    SELECT
        city,
        SUM(total_amount) AS total_revenue
    FROM dataset
    GROUP BY city
    ORDER BY total_revenue DESC
    LIMIT 1;

25. Do NOT return only the dimension when the question
    asks for a ranking.

26. Example of BAD SQL:

    SELECT city
    FROM dataset
    GROUP BY city
    ORDER BY SUM(total_amount) DESC
    LIMIT 1;

27. The preferred result should expose the metric:

    city | total_revenue

28. Use GROUP BY when the question asks for a metric
    broken down by a dimension.

29. Use aliases for calculated metrics so that the
    resulting dataset is easy to understand.

30. Do not add unnecessary columns that are unrelated
    to the user's question.


=========================================================
EXAMPLE
=========================================================

User question:

Which product sold the most units?

SQL:

SELECT
    product,
    SUM(quantity) AS total_units
FROM dataset
GROUP BY product
ORDER BY total_units DESC
LIMIT 1;


=========================================================
ANOTHER EXAMPLE
=========================================================

User question:

Which category has the highest revenue?

SQL:

SELECT
    category,
    SUM(total_amount) AS total_revenue
FROM dataset
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 1;


=========================================================
AVERAGE EXAMPLE
=========================================================

User question:

What is the average customer age?

SQL:

SELECT
    AVG(age) AS average_age
FROM dataset;


=========================================================
TREND EXAMPLE
=========================================================

User question:

Show monthly sales.

SQL:

SELECT
    purchase_month,
    SUM(total_amount) AS total_sales
FROM dataset
GROUP BY purchase_month;


=========================================================
FINAL INSTRUCTION
=========================================================

Generate the best SQLite SELECT query for:

{user_question}

Return ONLY the SQL query.
"""


    # =====================================================
    # CALL GEMINI
    # =====================================================

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=prompt
    )


    # =====================================================
    # GET RESPONSE
    # =====================================================

    sql_query = response.text


    print(
        "\n----------------------------------------"
    )

    print(
        "RAW GEMINI RESPONSE:"
    )

    print(
        repr(sql_query)
    )

    print(
        "----------------------------------------"
    )


    if sql_query is None:

        raise ValueError(
            "Gemini returned no response."
        )


    # =====================================================
    # CLEAN RESPONSE
    # =====================================================

    sql_query = clean_sql(
        sql_query
    )


    return sql_query